name: LinkUFront Deploy (Nuxt - Prebuilt)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop Nuxt SSR App
        run: sudo systemctl stop LinkuFrontEnd

      - name: Deploy prebuilt Nuxt app to Nginx
        run: |
          sudo rsync -avz --delete --exclude='.git' ./ /var/www/linkufront.blumita.com/public_html/LinkuFrontEnd
          sudo chmod -R 770 /var/www/linkufront.blumita.com/public_html/LinkuFrontEnd
          sudo chown -R www-data:www-data /var/www/linkufront.blumita.com/public_html/LinkuFrontEnd

      - name: Install dependencies on server
        run: |
          cd /var/www/linkufront.blumita.com/public_html/LinkuFrontEnd
          npm install

      - name: Start Nuxt SSR App
        run: |
          sudo systemctl start LinkuFrontEnd

      - name: Reload Nginx
        run: sudo systemctl reload nginx

      - name: Check application health
        run: curl -f https://linkufront.petoman.com || exit 1
